import { Service } from '../types';

export const SERVICES: Service[] = [
  // ═══════════════════════════════════════════
  // LICENCES
  // ═══════════════════════════════════════════
  {
    id: 'fssai-basic',
    name: 'FSSAI Basic Registration',
    price: 1000,
    priceLabel: '₹1,000',
    iconName: 'HiShieldCheck',
    category: 'Licences',
    description: 'FSSAI Basic Registration for small food businesses with turnover up to ₹12 Lakhs. Fast, hassle-free process with legal compliance guarantee.',
    imageUrl: '/posters/fssai.jpg',
    requirements: [
      'Aadhaar Card of the owner',
      'PAN Card',
      'Passport-size photograph',
      'Business address proof (Electricity bill / Rent agreement)',
      'Nature of business details',
      'List of food products to be handled',
    ],
  },
  {
    id: 'fssai-state',
    name: 'FSSAI State Licence',
    price: 9000,
    priceLabel: '₹9,000',
    iconName: 'HiShieldCheck',
    category: 'Licences',
    description: 'Complete FSSAI State Licence registration for medium food businesses with turnover ₹12 Lakhs – ₹20 Crore. End-to-end documentation support.',
    imageUrl: '/posters/fssai-design.jpg',
    requirements: [
      'Aadhaar Card & PAN Card of the owner',
      'Passport-size photograph',
      'Business entity proof (Partnership Deed / MOA / AOA)',
      'Food safety management plan',
      'List of food products with brand name',
      'NOC from local municipality',
      'Water testing report',
      'Business premises proof (Rent agreement / Ownership docs)',
    ],
  },
  {
    id: 'fssai-central',
    name: 'FSSAI Central Licence',
    price: 15000,
    priceLabel: '₹15,000',
    iconName: 'HiShieldCheck',
    category: 'Licences',
    description: 'FSSAI Central Licence for large businesses with turnover above ₹20 Crore or Import-Export operations. Full compliance assistance.',
    imageUrl: '/posters/fssai.jpg',
    requirements: [
      'Aadhaar Card & PAN Card of the owner/directors',
      'Passport-size photographs',
      'Business entity proof (Certificate of Incorporation / MOA / AOA)',
      'Food safety management plan / HACCP certification',
      'List of food products with brand names',
      'Import-Export Code (IEC) if applicable',
      'NOC from local municipality',
      'Blueprint/layout of the processing unit',
      'Water testing report',
      'Source of raw materials details',
    ],
  },
  {
    id: 'udyam-msme',
    name: 'UDYAM / MSME Registration',
    price: 300,
    priceLabel: '₹300',
    iconName: 'HiBuildingOffice2',
    category: 'Licences',
    description: 'Quick UDYAM/MSME registration for micro, small & medium enterprises. Get government certified in 24 hours.',
    imageUrl: '/posters/udyam-msme.jpg',
    requirements: [
      'Aadhaar Card of the owner',
      'PAN Card of the business / owner',
      'Business name & type',
      'Bank account details (Account number, IFSC)',
      'Investment & turnover details',
      'Business address',
    ],
  },
  {
    id: 'trade-licence',
    name: 'Trade Licence',
    price: 1500,
    priceLabel: '₹1,500',
    iconName: 'HiDocumentText',
    category: 'Licences',
    description: 'Apply for a Trade Licence for your business. Complete documentation support with fast government approval.',
    imageUrl: '/posters/trade-licence.jpg',
    requirements: [
      'Aadhaar Card & PAN Card',
      'Passport-size photograph',
      'Address proof of business premises',
      'Rent agreement / Ownership document',
      'Nature of trade / business activity',
      'NOC from landlord (if rented)',
    ],
  },
  {
    id: 'labour-licence',
    name: 'Labour Licence',
    price: 1500,
    priceLabel: '₹1,500',
    iconName: 'HiIdentification',
    category: 'Licences',
    description: 'Labour Licence application processing with all required documentation. 100% government-compliant filings.',
    imageUrl: '/posters/labour-licence.jpg',
    requirements: [
      'Aadhaar Card & PAN Card of the employer',
      'Business registration certificate',
      'List of employees with Aadhaar details',
      'Nature of work / establishment type',
      'Address proof of the establishment',
      'Passport-size photograph',
    ],
  },
  {
    id: 'driving-licence',
    name: 'Driving Licence',
    price: 6500,
    priceLabel: '₹6,500',
    iconName: 'HiIdentification',
    category: 'Licences',
    description: 'Complete assistance for New Driving Licence applications & Renewals. Slot booking, documentation, and RTO coordination.',
    imageUrl: '/posters/driving-licence.jpg',
    requirements: [
      'Aadhaar Card',
      'Age proof (Birth certificate / 10th marksheet)',
      'Address proof',
      'Passport-size photographs (4 copies)',
      'Learner\'s Licence (for permanent DL)',
      'Medical certificate (Form 1A)',
      'Existing DL (for renewal)',
    ],
  },

  // ═══════════════════════════════════════════
  // DOCUMENTS
  // ═══════════════════════════════════════════
  {
    id: 'pan-card',
    name: 'PAN Card (New / Correction)',
    price: 250,
    priceLabel: '₹250',
    iconName: 'HiCreditCard',
    category: 'Documents',
    description: 'New PAN card application or correction in existing PAN details. Quick processing and doorstep delivery support.',
    imageUrl: '/posters/pan-card.jpg',
    requirements: [
      'Aadhaar Card',
      'Passport-size photograph',
      'Date of birth proof (Birth certificate / 10th marksheet)',
      'Address proof (Aadhaar / Voter ID / Passport)',
      'Existing PAN Card (for corrections)',
    ],
  },
  {
    id: 'voter-id',
    name: 'Voter ID',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiIdentification',
    category: 'Documents',
    description: 'New Voter ID application, corrections, and address change assistance. Complete online filing support.',
    imageUrl: '/posters/voter-id.jpg',
    requirements: [
      'Aadhaar Card',
      'Passport-size photograph',
      'Age proof (Birth certificate / 10th marksheet)',
      'Address proof (Aadhaar / Electricity bill / Ration card)',
    ],
  },
  {
    id: 'aadhar-update',
    name: 'E-Aadhaar / Corrections',
    price: 250,
    priceLabel: '₹250',
    iconName: 'HiFingerPrint',
    category: 'Documents',
    description: 'Update your Aadhaar card — name, address, mobile number, date of birth, or photo correction. Assisted online update.',
    imageUrl: '/posters/aadhaar.jpg',
    requirements: [
      'Existing Aadhaar Card / Enrollment slip',
      'Mobile number linked to Aadhaar',
      'Supporting documents for the correction (e.g. Passport, Birth certificate for DOB change)',
      'Address proof (for address update)',
    ],
  },
  {
    id: 'e-shram-card',
    name: 'E-Shram Card',
    price: 100,
    priceLabel: '₹100',
    iconName: 'HiDocumentCheck',
    category: 'Documents',
    description: 'E-Shram card registration and printout for unorganized sector workers. Quick online registration.',
    imageUrl: '/posters/e-shram.jpg',
    requirements: [
      'Aadhaar Card',
      'Mobile number linked to Aadhaar',
      'Bank account details (Account number, IFSC)',
      'Occupation / skill type details',
    ],
  },
  {
    id: 'railway-divyang',
    name: 'Railway Divyangjan Card',
    price: 500,
    priceLabel: '₹500',
    iconName: 'HiTicket',
    category: 'Documents',
    description: 'Railway concession card for persons with disabilities. Complete assistance with application & documentation.',
    imageUrl: '/posters/divyangjan.jpg',
    requirements: [
      'Aadhaar Card',
      'Disability certificate from government hospital',
      'Passport-size photograph',
      'Age proof',
      'Address proof',
    ],
  },
  {
    id: 'marriage-certificate',
    name: 'Marriage Certificate',
    price: 3000,
    priceLabel: '₹3,000',
    iconName: 'HiHeart',
    category: 'Documents',
    description: 'Marriage certificate registration and processing. Complete documentation, affidavit support, and follow-up.',
    imageUrl: '/posters/marriage-certificate.jpg',
    requirements: [
      'Aadhaar Cards of both bride & groom',
      'Age proof of both (Birth certificate / 10th marksheet)',
      'Address proof of both parties',
      'Passport-size photos of bride & groom (4 each)',
      'Marriage invitation card',
      'Wedding photographs',
      'Two witnesses with Aadhaar Cards',
      'Affidavit of marriage (on stamp paper)',
    ],
  },
  {
    id: 'ration-card',
    name: 'Ration Card',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiClipboardDocumentList',
    category: 'Documents',
    description: 'New Ration Card application, name addition/deletion, and address corrections. Full assistance with online process.',
    requirements: [
      'Aadhaar Cards of all family members',
      'Address proof (Electricity bill / Gas bill)',
      'Income certificate',
      'Passport-size photographs of family head',
      'Existing Ration Card (for corrections/additions)',
      'Birth certificates of children (for additions)',
    ],
  },

  // ═══════════════════════════════════════════
  // ONLINE SERVICES
  // ═══════════════════════════════════════════
  {
    id: 'passport-normal',
    name: 'Passport Normal',
    price: 3100,
    priceLabel: '₹3,100',
    iconName: 'HiGlobeAlt',
    category: 'Online Services',
    description: 'End-to-end normal passport application assistance — new passport or renewal. Documentation, slot booking & police verification guidance.',
    imageUrl: '/posters/passport.jpg',
    requirements: [
      'Aadhaar Card',
      'PAN Card',
      'Voter ID / Ration Card',
      'Birth certificate / 10th marksheet (age proof)',
      'Passport-size photographs (white background)',
      'Address proof (Aadhaar / Electricity bill)',
      'Old Passport (for renewal)',
      'Marriage certificate (if name changed after marriage)',
    ],
  },
  {
    id: 'passport-tatkaal',
    name: 'Passport Tatkaal',
    price: 6000,
    priceLabel: '₹6,000',
    iconName: 'HiGlobeAlt',
    category: 'Online Services',
    description: 'Tatkaal (urgent) passport application assistance. Priority processing for time-sensitive travel needs.',
    imageUrl: '/posters/passport.jpg',
    requirements: [
      'Aadhaar Card',
      'PAN Card',
      'Birth certificate / 10th marksheet',
      'Passport-size photographs (white background)',
      'Address proof (Aadhaar / Electricity bill)',
      'Verification certificate from Gazetted officer / Notary',
      'Old Passport (for renewal)',
      'Annexure F (identity certificate)',
    ],
  },
  {
    id: 'us-visa-appointment',
    name: 'US Visa Appointment',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiPaperAirplane',
    category: 'Online Services',
    description: 'US Visa appointment slot booking assistance. DS-160 form filling, interview preparation guidance, and documentation support.',
    imageUrl: '/posters/us-visa.jpg',
    requirements: [
      'Valid Passport (6+ months validity)',
      'DS-160 confirmation page',
      'Visa fee payment receipt',
      'Passport-size photograph (US specs: 2×2 inch, white background)',
      'Employment / business proof',
      'Bank statements (last 6 months)',
      'ITR copies (last 3 years)',
      'Travel itinerary / invitation letter',
    ],
  },
  {
    id: 'train-tickets',
    name: 'Train Tickets',
    price: 100,
    priceLabel: '₹100',
    iconName: 'HiTicket',
    category: 'Travel & Bookings',
    description: 'IRCTC Train ticket booking assistance — Tatkal, general, and premium bookings. Confirmation guaranteed support.',
    imageUrl: '/posters/train-tickets.svg',
    requirements: [
      'Passenger name(s) and age(s)',
      'Travel date and preferred train',
      'Source and destination stations',
      'ID proof number (Aadhaar / PAN)',
      'Mobile number for ticket updates',
    ],
  },
  {
    id: 'flight-bookings',
    name: 'Flight Bookings',
    price: 500,
    priceLabel: '₹500',
    iconName: 'HiPaperAirplane',
    category: 'Travel & Bookings',
    description: 'Domestic and international flight ticket booking assistance. Best fare search and cancellation/rescheduling help.',
    imageUrl: '/posters/flight-bookings.svg',
    requirements: [
      'Passenger name(s) as per ID',
      'Travel dates and preferred airlines',
      'Source and destination airports',
      'Passport details (for international)',
      'Mobile number and email',
    ],
  },
  {
    id: 'insurance-services',
    name: 'Insurance Services',
    price: 299,
    priceLabel: '₹299',
    iconName: 'HiShieldCheck',
    category: 'Online Services',
    description: 'Life, health, and vehicle insurance policy assistance. New policy registration, renewals, and claim support.',
    imageUrl: '/posters/insurance-services.svg',
    requirements: [
      'Aadhaar Card & PAN Card',
      'Age proof',
      'Address proof',
      'Passport-size photograph',
      'Bank account details',
      'Vehicle RC book (for vehicle insurance)',
      'Previous policy details (for renewal)',
    ],
  },
  {
    id: 'loan-services',
    name: 'Loan Services',
    price: 500,
    priceLabel: '₹500',
    iconName: 'HiBanknotes',
    category: 'Online Services',
    description: 'Personal, business, home, and vehicle loan application assistance. Documentation and bank coordination support.',
    imageUrl: '/posters/loan-services.svg',
    requirements: [
      'Aadhaar Card & PAN Card',
      'Income proof (Salary slips / ITR)',
      'Bank statements (last 6 months)',
      'Address proof',
      'Employment / business proof',
      'Property documents (for home loan)',
      'Vehicle quotation (for vehicle loan)',
      'Passport-size photographs',
    ],
  },
  {
    id: 'pf-withdrawal',
    name: 'PF Withdrawal',
    price: 500,
    priceLabel: '₹500',
    iconName: 'HiCurrencyRupee',
    category: 'Online Services',
    description: 'Provident Fund (PF) claim and withdrawal assistance. UAN activation, KYC update, and online claim filing.',
    imageUrl: '/posters/pf-withdrawal.svg',
    requirements: [
      'UAN (Universal Account Number)',
      'Aadhaar Card (linked to UAN)',
      'PAN Card',
      'Bank account details (linked to UAN)',
      'Previous employer details',
      'Cancelled cheque / bank passbook',
    ],
  },
  {
    id: 'pmegp',
    name: 'PMEGP',
    price: 6999,
    priceLabel: '₹6,999',
    iconName: 'HiBuildingOffice2',
    category: 'Online Services',
    description: 'Prime Minister Employment Generation Programme (PMEGP) loan application. Project report preparation and bank linkage.',
    imageUrl: '/posters/pmegp.jpg',
    requirements: [
      'Aadhaar Card & PAN Card',
      'Caste certificate (for SC/ST/OBC/Minority)',
      'Educational qualification certificates',
      'Project report / business plan',
      'Passport-size photographs',
      'Bank account details',
      'Address proof of proposed unit',
      'EDP training certificate (if available)',
    ],
  },
  {
    id: 'kalyana-lakshmi',
    name: 'Kalyana Lakshmi',
    price: 500,
    priceLabel: '₹500',
    iconName: 'HiDocumentCheck',
    category: 'Online Services',
    description: 'Kalyana Lakshmi / Shaadi Mubarak scheme application assistance. Complete documentation and follow-up support.',
    imageUrl: '/posters/kalyana-lakshmi.jpg',
    requirements: [
      'Aadhaar Card of bride',
      'Aadhaar Card of mother / guardian',
      'Ration Card / Income certificate',
      'Caste certificate',
      'Age proof of bride (must be 18+)',
      'Bank account details (bride\'s account)',
      'Marriage invitation card / wedding photo',
      'SSC / birth certificate for age verification',
    ],
  },
  {
    id: 'ttd-seva-bookings',
    name: 'TTD Seva Bookings',
    price: 100,
    priceLabel: '₹100',
    iconName: 'HiStar',
    category: 'Travel & Bookings',
    description: 'Tirumala Tirupati Devasthanams (TTD) Seva, Darshan, and accommodation bookings. Quick slot confirmation.',
    imageUrl: '/posters/ttd-seva.svg',
    requirements: [
      'Aadhaar Card of all pilgrims',
      'Mobile number for OTP verification',
      'Preferred date of darshan / seva',
      'Number of pilgrims',
      'ID proof for accommodation booking',
    ],
  },
  {
    id: 'scholarship-services',
    name: 'Scholarship Services',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiAcademicCap',
    category: 'Online Services',
    description: 'State and national scholarship application assistance — Pre-Matric, Post-Matric, and merit-based scholarships.',
    imageUrl: '/posters/scholarship.jpg',
    requirements: [
      'Aadhaar Card of student',
      'Caste / Income certificate',
      'Previous year marksheet',
      'College / school admission letter / bonafide',
      'Bank account details (student\'s account)',
      'Passport-size photograph',
      'Fee receipt / tuition fee structure',
    ],
  },
  {
    id: 'online-applications',
    name: 'Online Applications',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiComputerDesktop',
    category: 'Online Services',
    description: 'General online form filling and application submission for any government or private portal. Job applications, exam registrations, and more.',
    requirements: [
      'Aadhaar Card',
      'Passport-size photograph (digital)',
      'Educational certificates as required',
      'Signature scan (digital)',
      'Application-specific documents',
    ],
  },

  // ═══════════════════════════════════════════
  // PRINTING
  // ═══════════════════════════════════════════
  {
    id: 'pvc-cards',
    name: 'PVC Cards',
    price: 100,
    priceLabel: '₹100',
    iconName: 'HiCreditCard',
    category: 'Printing',
    description: 'High-quality PVC card printing — ID cards, Aadhaar, PAN, business cards, and employee ID cards.',
    imageUrl: '/posters/pvc-cards.jpg',
    requirements: [
      'Soft copy of the card content / design',
      'Photograph (high resolution)',
      'Details to print (Name, ID number, etc.)',
    ],
  },
  {
    id: 'photo-frames',
    name: 'Photo Frames',
    price: 100,
    priceLabel: 'From ₹100',
    iconName: 'HiPhoto',
    category: 'Printing',
    description: 'Custom photo frames in various sizes — wall frames, desk frames, collage frames. Premium finish printing.',
    imageUrl: '/posters/photo-frames.jpg',
    requirements: [
      'High-resolution photographs (digital or physical)',
      'Preferred frame size',
      'Frame type (wall / desk / collage)',
      'Quantity required',
    ],
  },
  {
    id: 't-shirts-printing',
    name: 'T-Shirts Printing',
    price: 250,
    priceLabel: 'From ₹250',
    iconName: 'HiPrinter',
    category: 'Printing',
    description: 'Custom T-shirt printing with your designs, logos, or photos. Bulk orders available for events and businesses.',
    imageUrl: '/posters/tshirts.jpg',
    requirements: [
      'Design / logo / image file (high resolution)',
      'T-shirt color preference',
      'Size(s) required (S / M / L / XL / XXL)',
      'Quantity',
      'Placement (front / back / both)',
    ],
  },
  {
    id: 'fridge-magnets',
    name: 'Fridge Magnets',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiRectangleGroup',
    category: 'Printing',
    description: 'Custom fridge magnets with your photos, logos, or designs. Perfect for gifts, souvenirs, and branding.',
    imageUrl: '/posters/fridge-magnets.jpg',
    requirements: [
      'Photo / design file (high resolution)',
      'Preferred shape (round / square / custom)',
      'Size preference',
      'Quantity required',
    ],
  },
  {
    id: 'dvd-pendrive-transfer',
    name: 'DVD → Pen Drive Transfer',
    price: 300,
    priceLabel: '₹300',
    iconName: 'HiFilm',
    category: 'Printing',
    description: 'Transfer data from DVDs, CDs to Pen Drive or digital format. Photo, video, and document conversions available.',
    imageUrl: '/posters/pendrive.jpg',
    requirements: [
      'DVDs / CDs to be transferred',
      'Pen Drive (customer-provided or available at shop)',
      'Preferred output format (if specific)',
    ],
  },

  // ═══════════════════════════════════════════
  // REGISTRATION SERVICES
  // ═══════════════════════════════════════════
  {
    id: 'sale-deed',
    name: 'Sale Deed',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentText',
    category: 'Registration Services',
    description: 'Property Sale Deed drafting and registration. Complete stamp duty calculation, documentation, and SRO coordination.',
    requirements: [
      'Aadhaar Cards of buyer & seller',
      'PAN Cards of buyer & seller',
      'Passport-size photos of both parties',
      'Original property documents (previous deed)',
      'Encumbrance Certificate (EC)',
      'Market value / guideline value details',
      'Pattadar Passbook (for agricultural land)',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'gift-deed',
    name: 'Gift Deed',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentText',
    category: 'Registration Services',
    description: 'Property Gift Deed registration services. Legal drafting, valuation assistance, and sub-registrar office filing.',
    requirements: [
      'Aadhaar Cards of donor & donee',
      'PAN Cards of both parties',
      'Original property documents',
      'Encumbrance Certificate (EC)',
      'Relationship proof between donor & donee',
      'Passport-size photographs',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'partition-deed',
    name: 'Partition Deed',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentText',
    category: 'Registration Services',
    description: 'Property Partition Deed registration for joint property division. Legal documentation and family settlement support.',
    requirements: [
      'Aadhaar Cards of all parties',
      'PAN Cards of all parties',
      'Original property documents',
      'Encumbrance Certificate (EC)',
      'Family tree / relationship details',
      'Survey number & land extent details',
      'Passport-size photographs of all parties',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'family-release',
    name: 'Family Release',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiUserGroup',
    category: 'Registration Services',
    description: 'Family Release Deed registration — release of rights by family members on property. Full legal drafting and SRO filing.',
    requirements: [
      'Aadhaar Cards of all family members involved',
      'PAN Cards of all parties',
      'Original property documents',
      'Encumbrance Certificate (EC)',
      'Family tree / legal heir certificate',
      'Passport-size photographs',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'mortgage',
    name: 'Mortgage',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiHome',
    category: 'Registration Services',
    description: 'Property Mortgage registration services. Documentation for bank mortgage, equitable mortgage, and mortgage release.',
    requirements: [
      'Aadhaar Card & PAN Card of property owner',
      'Original property documents',
      'Encumbrance Certificate (EC)',
      'Bank loan sanction letter',
      'Property valuation report',
      'Passport-size photograph',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'bank-release',
    name: 'Bank Release',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiBanknotes',
    category: 'Registration Services',
    description: 'Bank Release / Mortgage Release deed registration. Complete assistance with NOC from bank and SRO filing.',
    requirements: [
      'Aadhaar Card & PAN Card of property owner',
      'NOC (No Objection Certificate) from the bank',
      'Original property documents',
      'Mortgage deed copy',
      'Loan closure certificate from bank',
      'Passport-size photograph',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'da-cum-gpa',
    name: 'DA cum GPA',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiScale',
    category: 'Registration Services',
    description: 'Development Agreement cum General Power of Attorney registration. Builder-landowner agreement documentation and filing.',
    requirements: [
      'Aadhaar Cards & PAN Cards of landowner & developer',
      'Original property / land documents',
      'Encumbrance Certificate (EC)',
      'Approved building plan (if available)',
      'Development agreement terms (sharing ratio, etc.)',
      'Passport-size photographs of both parties',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'gpa',
    name: 'GPA (General Power of Attorney)',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiKey',
    category: 'Registration Services',
    description: 'General Power of Attorney drafting and registration. Authorized representation for property and legal matters.',
    requirements: [
      'Aadhaar Card & PAN Card of the principal (person giving power)',
      'Aadhaar Card & PAN Card of the agent (person receiving power)',
      'Property documents (if property-related GPA)',
      'Details of powers to be granted',
      'Passport-size photographs of both parties',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'agreement-of-sale',
    name: 'Agreement of Sale',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiClipboardDocumentCheck',
    category: 'Registration Services',
    description: 'Agreement of Sale (AOS) drafting and registration. Pre-sale legal documentation with terms, conditions, and advance receipt.',
    requirements: [
      'Aadhaar Cards & PAN Cards of buyer & seller',
      'Property documents / title deed',
      'Encumbrance Certificate (EC)',
      'Sale terms (price, advance amount, timelines)',
      'Passport-size photographs of both parties',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'lease-rental-agreement',
    name: 'Lease / Rental Agreement',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentText',
    category: 'Registration Services',
    description: 'Lease and Rental Agreement drafting, notarization, and registration. Residential and commercial property agreements.',
    requirements: [
      'Aadhaar Cards of landlord & tenant',
      'Property ownership proof / previous agreement',
      'Rent amount & security deposit details',
      'Lease duration & terms',
      'Passport-size photographs of both parties',
      'Two witnesses with Aadhaar Cards',
    ],
  },
  {
    id: 'single-search',
    name: 'Single Search',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiMagnifyingGlass',
    category: 'Registration Services',
    description: 'Single Search report from Sub-Registrar Office. Verify property ownership history and transaction records.',
    requirements: [
      'Document number / year of registration',
      'Sub-Registrar Office (SRO) jurisdiction',
      'Property details (survey number, location)',
      'Names of parties involved (if known)',
    ],
  },
  {
    id: 'certified-copy',
    name: 'Certified Copy (CC)',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentCheck',
    category: 'Registration Services',
    description: 'Obtain Certified Copies (CC) of registered documents from the Sub-Registrar Office. Quick application and collection.',
    requirements: [
      'Document number & year of registration',
      'Sub-Registrar Office (SRO) name',
      'Applicant\'s Aadhaar Card',
      'Purpose of obtaining CC',
    ],
  },
  {
    id: 'market-value',
    name: 'Market Value',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiCurrencyRupee',
    category: 'Registration Services',
    description: 'Government Market Value / Guideline Value enquiry for properties. Calculate stamp duty and registration charges.',
    requirements: [
      'Property location / address',
      'Survey number / plot number',
      'Property type (residential / commercial / agricultural)',
      'Extent of the property (sq. yards / acres)',
    ],
  },
  {
    id: 'encumbrance-certificate',
    name: 'Encumbrance Certificate (EC)',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiMagnifyingGlass',
    category: 'Registration Services',
    description: 'Encumbrance Certificate (EC) application and procurement. Verify property is free from legal dues and mortgages.',
    requirements: [
      'Property document number & year',
      'Sub-Registrar Office (SRO) jurisdiction',
      'Property owner name',
      'Period for which EC is required',
      'Survey number & property address',
    ],
  },
  {
    id: 'society-firm-registration',
    name: 'Society / Firm Registration',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiBuildingOffice2',
    category: 'Registration Services',
    description: 'Society and Partnership Firm registration. MOA/AOA drafting, bylaws preparation, and Registrar of Firms filing.',
    requirements: [
      'Aadhaar Cards & PAN Cards of all partners / members',
      'Passport-size photographs of all partners',
      'Partnership Deed / MOA / AOA draft',
      'Registered office address proof',
      'Objectives / aims of the society or firm',
      'Minimum 7 members (for Society)',
      'Two witnesses with Aadhaar Cards',
    ],
  },

  // ═══════════════════════════════════════════
  // MEESEVA SERVICES
  // ═══════════════════════════════════════════
  {
    id: 'income-certificate',
    name: 'Income Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiCurrencyRupee',
    category: 'MeeSeva Services',
    description: 'Income Certificate application through MeeSeva. Required for scholarships, fee concessions, ration card, and government schemes.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Ration Card',
      'Salary certificate / Form 16 (for employed)',
      'Self-declaration (for self-employed)',
      'Passport-size photograph',
      'Address proof',
    ],
  },
  {
    id: 'caste-certificate',
    name: 'Caste Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiDocumentCheck',
    category: 'MeeSeva Services',
    description: 'Caste Certificate (SC/ST/BC) application through MeeSeva. Essential for education admissions, government jobs, and welfare schemes.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Father\'s / Family Caste Certificate (if available)',
      'Ration Card',
      'School Transfer Certificate (TC)',
      'Passport-size photograph',
      'Address proof',
    ],
  },
  {
    id: 'obc-certificate',
    name: 'OBC Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiDocumentCheck',
    category: 'MeeSeva Services',
    description: 'OBC (Other Backward Classes) Certificate through MeeSeva. Required for reservations in education and employment.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Father\'s Caste Certificate',
      'Ration Card',
      'Income Certificate',
      'School Transfer Certificate (TC)',
      'Passport-size photograph',
    ],
  },
  {
    id: 'residence-certificate',
    name: 'Residence / Nativity Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiHome',
    category: 'MeeSeva Services',
    description: 'Residence / Nativity Certificate through MeeSeva. Proof of domicile required for education, employment, and government services.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Ration Card',
      'Voter ID / Electricity bill as address proof',
      'Passport-size photograph',
      'Duration of residence details',
    ],
  },
  {
    id: 'ews-certificate',
    name: 'EWS Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiDocumentText',
    category: 'MeeSeva Services',
    description: 'Economically Weaker Section (EWS) Certificate through MeeSeva. Required for 10% reservation in education and government jobs.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Income Certificate (family income below ₹8 Lakh/year)',
      'Ration Card',
      'Self-declaration of assets',
      'Passport-size photograph',
      'Address proof',
    ],
  },
  {
    id: 'family-member-certificate',
    name: 'Family Member Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiUserGroup',
    category: 'MeeSeva Services',
    description: 'Family Member Certificate through MeeSeva. Official proof of family members for legal, educational, and government purposes.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Cards of all family members',
      'Ration Card',
      'Head of family\'s Voter ID',
      'Passport-size photograph of applicant',
    ],
  },
  {
    id: 'birth-certificate',
    name: 'Birth Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiDocumentText',
    category: 'MeeSeva Services',
    description: 'Birth Certificate application and correction through MeeSeva / GHMC. New registration, delayed registration, and name addition.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Hospital discharge summary / birth record',
      'Parents\' Aadhaar Cards',
      'Affidavit (for delayed registration)',
      'Address proof',
      'Passport-size photograph (for corrections)',
    ],
  },
  {
    id: 'death-certificate',
    name: 'Death Certificate',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiDocumentText',
    category: 'MeeSeva Services',
    description: 'Death Certificate application through MeeSeva / GHMC. New registration and corrections.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Hospital death summary / record',
      'Deceased person\'s Aadhaar Card',
      'Applicant\'s Aadhaar Card',
      'Address proof',
      'Affidavit (for delayed registration)',
    ],
  },
  {
    id: 'property-tax',
    name: 'Property Tax Payment',
    price: 100,
    priceLabel: '₹100',
    iconName: 'HiHome',
    category: 'MeeSeva Services',
    description: 'Property Tax payment assistance through GHMC / Municipal portals. Tax calculation, online payment, and receipt generation.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Property Tax ID / PTIN number',
      'Property owner\'s Aadhaar Card',
      'Previous tax receipt (if available)',
      'Property address details',
    ],
  },
  {
    id: 'water-connection',
    name: 'Water Connection',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiBeaker',
    category: 'MeeSeva Services',
    description: 'New water connection application, transfer, and disconnection through HMWSSB / Municipal authorities.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card of the applicant',
      'Property ownership proof / Rent agreement',
      'Recent property tax receipt',
      'Passport-size photograph',
      'No Objection Certificate from landlord (if rented)',
    ],
  },
  {
    id: 'tgspdcl-services',
    name: 'TGSPDCL Services',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiBolt',
    category: 'MeeSeva Services',
    description: 'Electricity services — new connection, name change, load enhancement, and tariff category change through TGSPDCL.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Property ownership proof / Rent agreement',
      'Recent electricity bill (for existing connections)',
      'Passport-size photograph',
      'Application form (available at MeeSeva center)',
    ],
  },
  {
    id: 'police-verification',
    name: 'Police Verification',
    price: 200,
    priceLabel: '₹200',
    iconName: 'HiShieldCheck',
    category: 'MeeSeva Services',
    description: 'Police Verification Certificate application for passport, employment, tenancy, and other purposes.',
    imageUrl: '/posters/meeseva.jpg',
    requirements: [
      'Aadhaar Card',
      'Address proof',
      'Passport-size photograph',
      'Purpose of verification (employment letter / passport copy)',
      'Mobile number for OTP',
    ],
  },

  // ═══════════════════════════════════════════
  // BHU BHARATI SERVICES
  // ═══════════════════════════════════════════
  {
    id: 'ror-1b',
    name: 'ROR / 1B Correction',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiMap',
    category: 'Bhu Bharati Services',
    description: 'ROR / 1B record correction services on Bhu Bharati Portal. Name, extent, and survey number corrections.',
    requirements: [
      'Pattadar Passbook',
      'Aadhaar Card of the Pattadar',
      'Existing ROR / 1B document',
      'Supporting documents for correction',
      'Survey number & village details',
    ],
  },
  {
    id: 'land-slots',
    name: 'Agriculture Land Slots Booking',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiMap',
    category: 'Bhu Bharati Services',
    description: 'Agriculture Land Slots Booking on Bhu Bharati Portal. Online slot reservation for land registration appointments.',
    requirements: [
      'Aadhaar Card of both buyer & seller',
      'Pattadar Passbook',
      'Survey number & land extent',
      'Village, Mandal & District details',
      'Mobile number linked to Aadhaar',
    ],
  },
  {
    id: 'pattadar-name-correction',
    name: 'Pattadar Name Correction',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiClipboardDocumentList',
    category: 'Bhu Bharati Services',
    description: 'Pattadar Passbook name correction on Bhu Bharati Portal. Update Pattadar details as per government records.',
    requirements: [
      'Existing Pattadar Passbook',
      'Aadhaar Card (with correct name)',
      'Survey number details',
      'Supporting name proof (Gazette notification / Court order)',
    ],
  },
  {
    id: 'land-details-search',
    name: 'Land Details Search',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiMagnifyingGlass',
    category: 'Bhu Bharati Services',
    description: 'Land Details Search on Bhu Bharati Portal — survey number lookup, ownership verification, and extent details.',
    requirements: [
      'Survey number',
      'Village name',
      'Mandal & District name',
      'Pattadar name (if known)',
    ],
  },
  {
    id: 'passbook-data-correction',
    name: 'Passbook Data Correction',
    price: 0,
    priceLabel: 'Custom',
    iconName: 'HiDocumentCheck',
    category: 'Bhu Bharati Services',
    description: 'Pattadar Passbook data correction on Bhu Bharati — update extent, survey number, village name, and other land records.',
    requirements: [
      'Existing Pattadar Passbook',
      'Aadhaar Card of the Pattadar',
      'Supporting documents for correction',
      'Survey number & village details',
      'Mobile number linked to Aadhaar',
    ],
  },
];

export const CATEGORIES = [
  'All',
  'Licences',
  'Documents',
  'Online Services',
  'MeeSeva Services',
  'Travel & Bookings',
  'Printing',
  'Registration Services',
  'Bhu Bharati Services',
] as const;

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Rajesh Kumar',
    quote: 'Got my FSSAI licence done in just 3 days! The team at EXTEND KART is incredibly professional and efficient. Highly recommended for any documentation work in Warangal.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't2',
    name: 'Priya Sharma',
    quote: 'Best service center in Warangal! Got my MSME registration for just ₹300. The staff is very helpful and guided me through the entire process. Will definitely come back.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't3',
    name: 'Mohammed Irfan',
    quote: 'Passport assistance was smooth and hassle-free. They handle everything from documentation to appointment booking. Very reasonable prices and excellent customer service.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't4',
    name: 'Suresh Reddy',
    quote: 'I needed a Trade Licence urgently for my new restaurant. EXTEND KART processed it within 2 days. Their knowledge of government processes saved me so much time and stress.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't5',
    name: 'Lakshmi Devi',
    quote: 'Got PVC cards and photo frames printed here — the quality is outstanding! Also got my Aadhaar updated on the same visit. One-stop shop for everything. Very convenient location.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't6',
    name: 'Venkat Rao',
    quote: 'Excellent service for my Labour Licence application. They took care of all the paperwork and followed up until it was approved. Truly professional team. Highly recommend!',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't7',
    name: 'Srinivas Goud',
    quote: 'Used their Sale Deed registration service. Very transparent process — they explained stamp duty, market value, everything clearly. Got it done without any hassle at the SRO office.',
    rating: 5,
    source: 'Google Review'
  },
  {
    id: 't8',
    name: 'Fatima Begum',
    quote: 'Applied for Kalyana Lakshmi scheme through EXTEND KART. They handled the entire documentation and I received the benefit on time. Very grateful for their service.',
    rating: 5,
    source: 'Google Review'
  },
];
