import React from 'react';
import {
  HiShieldCheck,
  HiBuildingOffice2,
  HiDocumentText,
  HiIdentification,
  HiGlobeAlt,
  HiTicket,
  HiCreditCard,
  HiFingerPrint,
  HiDocumentCheck,
  HiPrinter,
  HiCurrencyRupee,
  HiAcademicCap,
  HiPhoto,
  HiMap,
  HiHome,
  HiUserGroup,
  HiWrenchScrewdriver,
  HiBookOpen,
  HiClipboardDocumentList,
  HiArrowsRightLeft,
  HiMagnifyingGlass,
  HiBanknotes,
  HiPaperAirplane,
  HiDevicePhoneMobile,
  HiFilm,
  HiSquare3Stack3D,
  HiClipboardDocumentCheck,
  HiHandRaised,
  HiScale,
  HiKey,
  HiArchiveBox,
  HiRectangleGroup,
  HiComputerDesktop,
  HiHeart,
  HiStar,
} from 'react-icons/hi2';

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  HiShieldCheck,
  HiBuildingOffice2,
  HiDocumentText,
  HiIdentification,
  HiGlobeAlt,
  HiTicket,
  HiCreditCard,
  HiFingerPrint,
  HiDocumentCheck,
  HiPrinter,
  HiCurrencyRupee,
  HiAcademicCap,
  HiPhoto,
  HiMap,
  HiHome,
  HiUserGroup,
  HiWrenchScrewdriver,
  HiBookOpen,
  HiClipboardDocumentList,
  HiArrowsRightLeft,
  HiMagnifyingGlass,
  HiBanknotes,
  HiPaperAirplane,
  HiDevicePhoneMobile,
  HiFilm,
  HiSquare3Stack3D,
  HiClipboardDocumentCheck,
  HiHandRaised,
  HiScale,
  HiKey,
  HiArchiveBox,
  HiRectangleGroup,
  HiComputerDesktop,
  HiHeart,
  HiStar,
};

interface IconRendererProps {
  name: string;
  className?: string;
}

export default function IconRenderer({ name, className = '' }: IconRendererProps) {
  const IconComponent = ICON_MAP[name] || HiDocumentText;
  return <IconComponent className={className} />;
}
